"""Initial migration.

Revision ID: e229ac816508
Revises: 7bae8985af88
Create Date: 2024-10-16 21:12:58.599543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e229ac816508'
down_revision = '7bae8985af88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('merchant_request_id')
        batch_op.drop_column('checkout_request_id')

    # ### end Alembic commands ###
